### ISSUE TITLE
CRITICAL PRIORITY

### ISSUE THREAD

**Issue by bioender173** [sortofasian/d3#16] opened 2022-09-03 07:54 UTC
In order:

Fix time-lapse

Add the rest of the shipping sizes.

Make website work for mobile.

Fix bot

**Comment by bioender173** [comment] 2022-09-03 08:04
.

**Comment by sortofasian** [comment] 2022-09-03 11:42
Duplicate of #2;
Timelapse is fixed in latest dev build
Creating new issue for bot

**Closed by sortofasian** 2022-09-03 11:42 UTC
